clickhouse: myhelmapp

namespace: default

configmap:
  name: helmappconfigmapv1.1
  data:
  
    HOT_DATA_SIZE: "5GB"
    COLD_DATA_SIZE: "10GB"
    MOVE_FACTOR: "0.2"

image:
  name: clickhouse/clickhouse-server
  tag: head-alpine
