apiVersion: v1
kind: Service
metadata:
  name: { { .Values.clickhouse } }
  namespace: { { .Values.namespace } }
spec:
  ports:
    - port: 80
      protocol: TCP
  selector:
    app: { { .Values.clickhouse } }
